import type { Metadata } from "next";
import SideNav from "./SideNav";
import React from "react";

export const metadata: Metadata = {
  title: "Profile | Resume Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <div className="flex">
      <div className="w-1/5">
        <SideNav />
      </div>{" "}
      <div className="w-4/5 p-5">{children}</div>
    </div>
  );
}
